### PR TITLE
Changes related to Notification Upgrade

### PR DESCRIPTION
**Pull request by tsrahm**
Remove trap when drawer closes and pass in callback to handle closed from within.
I identified these while doing the Notification upgrade. If the trap is not removed, the focusables array will contain the trap only every time the drawer is opened subsequent to the first open. The callback is used to change the view from the archive list to the current list when the drawer is closed using the trap while viewing the archive list.

### CODE REVIEW

**Comment by StommePoes** [comment]
Something doesn't work with this.
When I run contextual-help calling your branch locally, I get the drawer working correctly only once. When I close the drawer, focus does not go back to the on-page trigger. Tabbing to the button again to open the drawer, focus no longer goes to the drawer.

It might be that con-help needs something somewhere to recognise the callback? I'm not sure where the disconnect is.
screenshot devtools error message after attempting to open the drawer a second time: Uncaught TypeError: this.cb is not a function at Drawer.js

**Comment by tsrahm** [comment]
The callback is being passed into Drawer, but it's not required, so I added a conditional so it only fires if it exists. This change should eliminate any impact on con-help due to the callback.

**Comment by StommePoes** [comment]
Seems to run ok over here. Looks good.

**Comment by mhomolak** [comment]
Closing due to Drawer being re-written in DES-478.

**Pull request merged**
