### PR TITLE
fix: focus cycles through Drawer - Des 372

### PR DESCRIPTION
**Pull request by StommePoes**

### CODE REVIEW

**Comment by StommePoes** [comment]
Trying to add unit tests for this one but may not be possible with karma/Phantom.

**Comment by JasonLantz** [comment]
code looks good on this one as well...

**Comment by wyseguyonline** [comment]
Approved.

**Comment by StommePoes** [comment]
I can't unit test the focus cycling, that will have to be done via Selenium it seems. Turns out testing for focus itself is iffy-- with a real browser, that browser application has to have application focus for any real focus to be measured with JS :/

**Comment by StommePoes** [comment]
Blocked: unit tests all fail.

**Pull request closed without merging**
